app/Http/routes.php
<?php
use App\Option;
use App\Site;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('sites/testing', 'SiteController@testing');

#Route::get('sites/restart', 'SiteController@restart');

Route::get('sites/get_db_info', 'SiteController@get_db_info');

Route::get('sites/get_cms_info', 'SiteController@get_cms_info');

Route::get('sites/export','SiteController@export');

Route::get('sites/addkeys','SiteController@addkeys');

Route::get('sites/add_alias','SiteController@add_alias');

Route::get('sites/get_sites','SiteController@get_sites');

Route::get('sites/trash','SiteController@trash');

Route::get('sites/suspend','SiteController@suspend');

Route::get('sites/site_continue','SiteController@site_continue');

Route::get('sites/restore','SiteController@restore');

Route::resource("sites","SiteController");

Route::resource("options","OptionController");

Route::resource("apps","AppController"); 

Route::resource("actions","ActionController");

Route::resource("adomains","AdomainController");

Route::resource("apps_actions","AppsActionController");

Route::get('contact', 'WelcomeController@contact');

#Route::get('/', function () {
#    return view('sites');
#});

#Route::get('/', 'UploadController@index');
#Route::post('upload/add', 'UploadController@uploadFiles');


#Route::get('/testing', function () {
#    return response()->json(['name' => 'Abigail', 'state' => 'CA']);
#});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::get('users', 'AdminController@list_users');
Route::get('edit_user', 'AdminController@edit_user');
Route::get('force_delete', 'AdminController@force_delete');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');


Route::get('/get_domains', function () {
	
	$sites = Site::orderBy('id', 'desc')->get();
    return response()->json($sites);
});

Route::get('/get_massives', function () {
	$app_root = Option::where('option_name','app_root')->first()->option_value;
	
	$result = shell_exec("find {$app_root} -maxdepth 1 -type f -name '*.tar.gz'");
	#$result = $result . shell_exec("find {$app_root}/Massive/public/uploads -maxdepth 1 -type f -name '*.tar.gz'");
	
	$result = str_replace("{$app_root}/","",$result);
	$result = str_replace('/',"",$result);
	#$aux = str_replace("/wp-config.php","",$aux);
	#$result = explode("\n",$aux);
	$result = explode("\n",$result);
    return response()->json($result);
});


Route::get('/', array('as' => 'sites.index', 'uses' => 'SiteController@index'));
Route::get('/home', array('as' => 'sites.index', 'uses' => 'SiteController@index'));

app/Adomain.php
<?php

namespace App;
use App\Site;
use Log;
use Illuminate\Database\Eloquent\Model;

class Adomain extends Model
{
    //
	public function massive_redirect(){
				
		$os = Option::where('option_name','os')->first()->option_value;
		$adomain_name =  $this->name;
		$site = Site::findOrFail($this->site_id); 
		$site_url = $site->url;
		$app_root = Option::where('option_name','app_root')->first()->option_value;
		$server_conf = Option::where('option_name','server_conf')->first()->option_value;
		$id = $this->id;
		$filename = str_replace(".","",$adomain_name);
		$filename = "redirect" . $filename;
			
		$command = "sh {$app_root}/Pete/scripts/add_redirect.sh -v {$os} -n {$adomain_name} -u {$site_url} -r {$app_root} -a {$server_conf} -s {$id} -x {$filename}";
		
		Log::info('Pete Command: ' . $command);
		
		$this->output = shell_exec($command);
		$this->save();
		$site->restart_server();
	}
	
	
    //
	public function massive_delete_redirect(){
				
		$os = Option::where('option_name','os')->first()->option_value;
		$adomain_name =  $this->name;
		$site = Site::findOrFail($this->site_id); 
		$site_url = $site->url;
		$app_root = Option::where('option_name','app_root')->first()->option_value;
		$server_conf = Option::where('option_name','server_conf')->first()->option_value;
		$id = $this->id;
		$filename = str_replace(".","",$adomain_name);
		
		$command = "sh {$app_root}/Pete/scripts/delete_redirect.sh -v {$os} -n {$adomain_name} -u {$site_url} -r {$app_root} -a {$server_conf} -s {$id} -x {$filename}";
		
		//Log::info('Pete Command: ' . $command);
		
		$this->output = shell_exec($command);
		$this->save();
		
		$site->restart_server();
	}
}

app/Http/Controllers/AdomainController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Log;
use App\Adomain;
use Illuminate\Http\Request;
use App\User;
use Validator;

class AdomainController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$adomains = Adomain::orderBy('id', 'desc')->paginate(10);

		return view('adomains.index', compact('adomains'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('adomains.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		
		$adomain = new Adomain();
		
		$adomain->name = $request->input("name");
		$adomain->site_id = $request->input("site_id");
		
		
      $validator = Validator::make($request->all(), [
               'name' => 'required|unique:adomains',
      ]);

      if ($validator->fails()) {
        return redirect("sites/{$adomain->site_id}/edit")
        ->withErrors($validator)
        ->withInput();
      }
		
		$adomain->save();
		$adomain->massive_redirect();
		
		return redirect("sites/{$adomain->site_id}/edit");
		
		//return redirect()->route('adomains.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$adomain = Adomain::findOrFail($id);

		return view('adomains.show', compact('adomain'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$adomain = Adomain::findOrFail($id);

		return view('adomains.edit', compact('adomain'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$adomain = Adomain::findOrFail($id);

		$adomain->name = $request->input("name");

		$adomain->save();

		return redirect()->route('adomains.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$adomain = Adomain::findOrFail($id);
		$site_id = $adomain->site_id;
		
		$adomain->massive_delete_redirect();
		$adomain->delete();
		
		return redirect("sites/{$site_id}/edit");
		
		//return redirect()->route('adomains.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/adomains/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Adomains / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('adomains.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('adomains.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/adomains/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Adomains / Edit #{{$adomain->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('adomains.update', $adomain->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ $adomain->name }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('adomains.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/adomains/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Adomains
            <a class="btn btn-success pull-right" href="{{ route('adomains.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($adomains->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($adomains as $adomain)
                            <tr>
                                <td>{{$adomain->id}}</td>
                                <td>{{$adomain->name}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('adomains.show', $adomain->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('adomains.edit', $adomain->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('adomains.destroy', $adomain->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $adomains->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/adomains/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Adomains / Show #{{$adomain->id}}</h1>
        <form action="{{ route('adomains.destroy', $adomain->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('adomains.edit', $adomain->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$adomain->name}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('adomains.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection