app/Http/routes.php
<?php
use App\Option;
use App\Site;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('sites/testing', 'SiteController@testing');

#Route::get('sites/restart', 'SiteController@restart');

Route::get('sites/get_db_info', 'SiteController@get_db_info');

Route::get('sites/get_cms_info', 'SiteController@get_cms_info');

Route::get('sites/export','SiteController@export');

Route::get('sites/addkeys','SiteController@addkeys');

Route::get('sites/add_alias','SiteController@add_alias');

Route::get('sites/get_sites','SiteController@get_sites');

Route::get('sites/trash','SiteController@trash');

Route::get('sites/suspend','SiteController@suspend');

Route::get('sites/site_continue','SiteController@site_continue');

Route::get('sites/restore','SiteController@restore');

Route::resource("sites","SiteController");

Route::resource("options","OptionController");

Route::resource("apps","AppController"); 

Route::resource("actions","ActionController");

Route::resource("adomains","AdomainController");

Route::resource("apps_actions","AppsActionController");

Route::get('contact', 'WelcomeController@contact');

#Route::get('/', function () {
#    return view('sites');
#});

#Route::get('/', 'UploadController@index');
#Route::post('upload/add', 'UploadController@uploadFiles');


#Route::get('/testing', function () {
#    return response()->json(['name' => 'Abigail', 'state' => 'CA']);
#});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::get('users', 'AdminController@list_users');
Route::get('edit_user', 'AdminController@edit_user');
Route::get('force_delete', 'AdminController@force_delete');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');


Route::get('/get_domains', function () {
	
	$sites = Site::orderBy('id', 'desc')->get();
    return response()->json($sites);
});

Route::get('/get_massives', function () {
	$app_root = Option::where('option_name','app_root')->first()->option_value;
	
	$result = shell_exec("find {$app_root} -maxdepth 1 -type f -name '*.tar.gz'");
	#$result = $result . shell_exec("find {$app_root}/Massive/public/uploads -maxdepth 1 -type f -name '*.tar.gz'");
	
	$result = str_replace("{$app_root}/","",$result);
	$result = str_replace('/',"",$result);
	#$aux = str_replace("/wp-config.php","",$aux);
	#$result = explode("\n",$aux);
	$result = explode("\n",$result);
    return response()->json($result);
});


Route::get('/', array('as' => 'sites.index', 'uses' => 'SiteController@index'));
Route::get('/home', array('as' => 'sites.index', 'uses' => 'SiteController@index'));

resources/views/apps/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Apps / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('apps.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('body')) has-error @endif">
                       <label for="body-field">Body</label>
                    <textarea class="form-control" id="body-field" rows="3" name="body">{{ old("body") }}</textarea>
                       @if($errors->has("body"))
                        <span class="help-block">{{ $errors->first("body") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('apps.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/apps/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Apps / Edit #{{$app->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('apps.update', $app->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ $app->name }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('body')) has-error @endif">
                       <label for="body-field">Body</label>
                    <textarea class="form-control" id="body-field" rows="3" name="body">{{ $app->body }}</textarea>
                       @if($errors->has("body"))
                        <span class="help-block">{{ $errors->first("body") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('apps.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/apps/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <img src="/massive.png" alt="Massive Server" style="width:70px;height:70px;">
            <a class="btn btn-success pull-right" href="{{ route('apps.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($apps->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                        <th>BODY</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($apps as $app)
                            <tr>
                                <td>{{$app->id}}</td>
                                <td>{{$app->name}}</td>
                    <td>{{$app->body}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('apps.show', $app->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('apps.edit', $app->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('apps.destroy', $app->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $apps->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/apps/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Apps / Show #{{$app->id}}</h1>
        <form action="{{ route('apps.destroy', $app->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('apps.edit', $app->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="name">NAME</label>
                     <p class="form-control-static">{{$app->name}}</p>
                </div>
                    <div class="form-group">
                     <label for="body">BODY</label>
                     <p class="form-control-static">{{$app->body}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('apps.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection