app/Http/routes.php
<?php
use App\Option;
use App\Site;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('sites/testing', 'SiteController@testing');

#Route::get('sites/restart', 'SiteController@restart');

Route::get('sites/get_db_info', 'SiteController@get_db_info');

Route::get('sites/get_cms_info', 'SiteController@get_cms_info');

Route::get('sites/export','SiteController@export');

Route::get('sites/addkeys','SiteController@addkeys');

Route::get('sites/add_alias','SiteController@add_alias');

Route::get('sites/get_sites','SiteController@get_sites');

Route::get('sites/trash','SiteController@trash');

Route::get('sites/suspend','SiteController@suspend');

Route::get('sites/site_continue','SiteController@site_continue');

Route::get('sites/restore','SiteController@restore');

Route::resource("sites","SiteController");

Route::resource("options","OptionController");

Route::resource("apps","AppController"); 

Route::resource("actions","ActionController");

Route::resource("adomains","AdomainController");

Route::resource("apps_actions","AppsActionController");

Route::get('contact', 'WelcomeController@contact');

#Route::get('/', function () {
#    return view('sites');
#});

#Route::get('/', 'UploadController@index');
#Route::post('upload/add', 'UploadController@uploadFiles');


#Route::get('/testing', function () {
#    return response()->json(['name' => 'Abigail', 'state' => 'CA']);
#});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::get('users', 'AdminController@list_users');
Route::get('edit_user', 'AdminController@edit_user');
Route::get('force_delete', 'AdminController@force_delete');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');


Route::get('/get_domains', function () {
	
	$sites = Site::orderBy('id', 'desc')->get();
    return response()->json($sites);
});

Route::get('/get_massives', function () {
	$app_root = Option::where('option_name','app_root')->first()->option_value;
	
	$result = shell_exec("find {$app_root} -maxdepth 1 -type f -name '*.tar.gz'");
	#$result = $result . shell_exec("find {$app_root}/Massive/public/uploads -maxdepth 1 -type f -name '*.tar.gz'");
	
	$result = str_replace("{$app_root}/","",$result);
	$result = str_replace('/',"",$result);
	#$aux = str_replace("/wp-config.php","",$aux);
	#$result = explode("\n",$aux);
	$result = explode("\n",$result);
    return response()->json($result);
});


Route::get('/', array('as' => 'sites.index', 'uses' => 'SiteController@index'));
Route::get('/home', array('as' => 'sites.index', 'uses' => 'SiteController@index'));

app/Http/Controllers/SiteController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Log;
use App\Site;
use App\Adomain;
use App\Action;
use App\Secure;
use App\User;
use Input;
use Response;
use App\App;
use Validator;
use App\Option;
use DB;
use Illuminate\Support\Facades\Auth;

use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class SiteController extends Controller {

	
	public function __construct()
	    {
	        #$this->middleware('csrf');
	        $this->middleware('auth');
			
	    }
		
			
	public function get_cms_info(){
			$secure = new Secure();
			$site = Site::findOrFail(Input::get('id'));
		
			$user_decrypt = $secure->mc_decrypt($site->cms_user);
			$password_decrypt = $secure->mc_decrypt($site->cms_password);
		
		  Log::info('Site IDX' . $site->id);
		 
		  return response()->json(['cms_user' => $user_decrypt,"cms_password" => $password_decrypt]);	 
		  
	}
	
	public function get_db_info(){
	  $secure = new Secure();
	  $site = Site::findOrFail(Input::get('id'));
		
	  $db_name_decrypt = $secure->mc_decrypt($site->db_name);
	  $db_user_decrypt = $secure->mc_decrypt($site->db_user);
	  $db_password_decrypt = $secure->mc_decrypt($site->db_password);
		
	  return response()->json(['db_name' => $db_name_decrypt,"db_user" => $db_user_decrypt, "db_password" => $db_password_decrypt]);	 
	  #return response()->json(['ok' => "ok"]);
	  #return response()->json(['name' => 'Abigail', 'state' => 'CA']);
	}
	
	public function export(){
		
		Log::info('EXPORT' . Input::get('id'));
		
		$site = Site::findOrFail(Input::get('id'));
		
		$site->export_massive();
		$exporturl = $site->file_to_download;
		
		$sites = Site::orderBy('id', 'desc')->paginate(10);
		
		return view('sites.index', compact('sites','exporturl'));
	  
	}
	
	public function trash(){
		$user = Auth::user();
		
		if($user->admin){
		  $sites = Site::onlyTrashed()->orderBy('id', 'desc')->paginate(10);
		}else{
		  $sites = Site::onlyTrashed()->orderBy('id', 'desc')->where('user_id', $user->id)->paginate(10);	
		}
		
		return view('sites.trash', compact('sites'));
	  
	}
	
	
	public function suspend(){
		
		$site = Site::findOrFail(Input::get('id'));
		$site->suspend = true;
		$site->massive_suspend();
		$site->save();
		
		return redirect()->route('sites.index')->with('message', 'Item updated successfully.');
	  
	}
	
	public function site_continue(){
		
		$site = Site::findOrFail(Input::get('id'));
		$site->suspend = false;
		
		$site->massive_continue();
		
		$site->save();
		
		return redirect()->route('sites.index')->with('message', 'Item updated successfully.');
	  
	}
	
	
	
	public function get_sites(){
		
		if (Input::get('app_name') == "Wordpress"){
		  //$result = DB::select('select id,name from sites where app_id = ?', [1]);
		  $result = Site::where('app_id', 1)->get();
		}else if(Input::get('app_name') == "Drupal"){
		  $result = Site::where('app_id', 2)->get();
		}else{
		  $result = Site::withTrashed()->orderBy('id', 'desc')->get(['id','name','url']);
		}
		
	    return response()->json($result);
	  
	}
	
	public function restore(){
		$site = Site::withTrashed()->findOrFail(Input::get('id'));
		$exporturl = "";
		$site->url = str_replace("massivetrash","",$site->url);
		$site->massive_restore();
		$site->restore();
		
		$user = Auth::user();
		if($user->admin){
		  $sites = Site::orderBy('id', 'desc')->paginate(10);
		}else{
		  #global template sites
		  $sites = Site::orderBy('id', 'desc')->where('user_id', $user->id)->paginate(10);	
		}
		
		return view('sites.index', compact('sites','exporturl'));
	}
	
	public function addkeys(){
		
		Log::info('EXPORT' . Input::get('id'));
		
		$site = Site::findOrFail(Input::get('id'));
		
		$secure = new Secure();
	
		$site->cms_user = $secure->mc_decrypt($site->cms_user);
		$site->cms_password = $secure->mc_decrypt($site->cms_password);
		
		return view('sites.addkeys', compact('site'));
	  
	}
	
	public function add_alias(){
		
		Log::info('EXPORT' . Input::get('id'));
		
		$site = Site::findOrFail(Input::get('id'));
		
		$secure = new Secure();
	
		$site->cms_user = $secure->mc_decrypt($site->cms_user);
		$site->cms_password = $secure->mc_decrypt($site->cms_password);
		
		return view('sites.addkeys', compact('site'));
	  
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$user = Auth::user();
		if($user->admin){
		  $sites = Site::orderBy('id', 'desc')->paginate(10);
		}else{
		  #global template sites
		  $sites = Site::orderBy('id', 'desc')->where('user_id', $user->id)->paginate(10);	
		}
		$first_time = "";
		$first_time = session('first_time');		
		$exporturl = "";
		
		return view('sites.index', compact('sites','exporturl','current_user','first_time'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{   
		#Url Template
		$url_template = Site::UrlTemplate();
		$drupal_support = Site::DrupalSupport();
		
		$actions = Action::orderBy('id', 'desc')->paginate(10);
		$apps = App::orderBy('id', 'desc')->paginate(10);
		$root = shell_exec('pwd');
		$root = str_replace("/massive/public","",$root);
		
		//$sites_count = Site::count();
		//Utilizamos el ultimo record de la query ordenando ASC
		//Para funciones 
		
		
		$url_template_string = Site::getUrlTemplateWithID();
		
		return view('sites.create',compact('actions','apps','output','url_template','drupal_support','sites_count','url_template_string'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		
		$site = new Site();
		$user = Auth::user();
		
		if($request->input("url_template") == "true"){
		  $url_template = Option::where('option_name','url_template')->first()->option_value;	
		}else{
		  $url_template = false;
	    }
		
		$appid= App::where('name',$request->input("app_name"))->first()->id;
		$actionid= Action::where('name',$request->input("action_name"))->first()->id;
		
		$site->app_name = $request->input("app_name");
		$site->action_name = $request->input("action_name");
		
		$site->to_clone_project = $request->input("to_clone_project");
		$site->name = $request->input("name");
		$site->to_import_project = $request->input("to_import_project");
        
		$site->action_id = $actionid;
		$site->app_id = $appid;
		$site->user_id = $user->id;
		
		$site->url = "template";
		
		if($request->file('filem')!= ""){
			
			$file = $request->file('filem');
	        // SET UPLOAD PATH
	        $destinationPath = 'uploads';
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
	        $fileName = rand(11111, 99999) . '.' . "tar.gz";
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$site->zip_file_url = $fileName;
		}
	
		#$site->output = shell_exec(Site::massive_exec_shell($site));
		
		if($url_template){
  	      $validator = Validator::make($request->all(), [
  	               'name' =>  array('required', 'regex:/^[a-zA-Z0-9-_]+$/','unique:sites'),
  	      ]);

  	      if ($validator->fails()) {
  	        return redirect('sites/create')
  	        ->withErrors($validator)
  	        ->withInput();
  	      }
		}else{
			
	      $validator = Validator::make($request->all(), [
				   'name' =>  array('required', 'regex:/^[a-zA-Z0-9-_]+$/','unique:sites'),
	               'url' => 'required|unique:sites',
	      ]);

	      if ($validator->fails()) {
	        return redirect('sites/create')
	        ->withErrors($validator)
	        ->withInput();
	      }
		
		}
		
		if($site->save()){
			
			if($request->input("url")){
				$site->url = $request->input("url");
			}else{
			    $site->url = Site::getUrlTemplateWithID();
			}	
			
		  $site->massive_logic();
		
		}
		
		return redirect()->route('sites.show', [$site->id]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show(Request $request, $id)
	{
		$site = Site::findOrFail($id);
		$root = shell_exec('pwd');
		
		$root = shell_exec('pwd');
		$root = str_replace("/massive/public","",$root);
		
		$output = shell_exec('scripts/test -u jsmith -p notebooks -d 10-20-2011 -f pdf');
		
		#$mysql_bin = Option::where('option_name','mysql_bin')->first()->option_value;
		
		#Se puede encriptar
		$request->session()->put('os', 'centos7');
		
		return view('sites.show', compact('site','output'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//$adomains = Adomain::orderBy('id', 'desc')->get();
		
		
		$current_user = Auth::user();
		
		$secure = new Secure();
		
		
		$site = Site::findOrFail($id);
		$adomains = Adomain::orderBy('id', 'desc')->where('site_id', $site->id)->get();	
		$user_decrypt = $secure->mc_decrypt($site->cms_user);
		$password_decrypt = $secure->mc_decrypt($site->cms_password);
		
        $users = User::orderBy('id', 'desc')->get();
		
		
		return view('sites.edit', compact('site','users','current_user','user_decrypt','password_decrypt','adomains'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$site = Site::findOrFail($id);
	
	    if(($request->input("url") != "") & ($request->input("url") != $site->url)){
			
	    	$past_url = $site->url;
			$site->url = $request->input("url");
			
		    $validator = Validator::make($request->all(), [
		               'url' => 'required|unique:sites',
		    ]);

		    if ($validator->fails()) {
		      return redirect("sites/{$site->id}/edit")
		      ->withErrors($validator)
		      ->withInput();
		    }
			
		  $site->massive_move($past_url);
	    }
		

resources/views/sites/addkeys.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Sites / Add Keys #{{$site->id}}</h1>
    </div>
@endsection

@section('content')
<div id="loading_area"></div>
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('sites.update', $site->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    <div class="form-group">
                       <label for="url-field">CMS User</label>
                    <input type="text" id="cms_user-field" name="cms_user" class="form-control" value="{{ $site->cms_user }}"/>
                      
                    </div>
					
					
                    <div class="form-group ">
                       <label for="cms_password-field">CMS Password</label>
                    <input type="text" id="cms_password-field" name="cms_password" class="form-control" value="{{ $site->cms_password }}"/>
                      
                    </div>
                    
                <div class="well well-sm">
                    <button type="submit" id ="update_button" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('sites.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
	
	
	<script>
	
	var createsw = false;
	
  $("#update_button").click(function() {
	  
	  if(createsw == false){

		 $("#loading_area").html('<div id="loading_div"></div>');
	  
	  	if($('#url-field').attr('success')=="false"){
		  alert("There is a site or project with the same URL. Please change it!");
		  return false;
		  }
	  
	  }else{
	  	console.log("Wait Please!!")
		return false;
	  }
	  
	  createsw = true;
  });
	
 $('#url-field').observe_field(1, function( ) {
	
  $("#loading_area").html('<div id="loading_div"></div>'); 
    
   
   sw = 0;
  $.ajax({
        url: "/get_domains",
        type: "get",
    datatype: 'json',
        success: function(data){
			$("#loading_area").html('');
		
	        for(p in data){
				
				console.log(data[p].url);
				
				if(data[p].url == $('#url-field').val()){
					
					sw = 1;
					$('#url-field').removeClass("great_name");
					$('#url-field').addClass("wrong_name");
					$('#url-field').attr( "success", "false" );
					$('#url_error_area').html('<label id="name-field-error" class="error" for="name-field">There Site with the same domain. Please change it!</label>');
				}
				
	        }
	        if(sw == 0){
				$('#url-field').removeClass("wrong_name");
	            $('#url-field').addClass("great_name");
				$('#url-field').attr( "success", "true" );
				$('#url_error_area').html("");
	        }
			
			
		}
	});
	 
 });
	
	</script>
	
@endsection

resources/views/sites/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
    <h3> Create new site
	</h3>
	
	<div id="loading_area"></div>
	
    </div>
	
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">
			
			@if($drupal_support)
			
                @include('sites/multiplecms')
			
			@else
			
				@include('sites/pete')
			
			@endif

             

        </div>
    </div>
	
@endsection

resources/views/sites/edit.blade.php
@extends('layout')

@section('header')
    
@endsection

@section('content')
<div id="loading_area"></div>
    @include('error')
	
	@if($current_user->admin)
    <div class="row">
        <div class="col-md-12">
			<br /><br />
            <form action="{{ route('sites.update', $site->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
					
					
 			   		
	                <div class="form-group">
                         <label for="user_id-field">Select user</label>
							<select class="form-control" id = "user_id-field" name ="user_id" required>
						
							    @foreach($users as $user)
								@if($user->id == $site->user_id)
							      <option value="{{$user->id}}" selected>{{$user->name}}</option>
								@else
								  <option value="{{$user->id}}">{{$user->name}}</option>
								@endif
							  @endforeach
							</select>
	                 </div>
                    
           
                    <button type="submit" id ="update_button" class="btnpete">Assign to user</button>
                    
         
            </form>
			<br /><br />
        </div>
    </div>
	
	 @endif
	 
     <div class="row">
         <div class="col-md-12">
			 
			  <label for="user_id-field">Alias Domains</label>
			 
             @if($adomains->count())
                 <table class="table table-condensed table-striped">
                  

                     <tbody>
                         @foreach($adomains as $adomain)
                             <tr>
                                
                                 <td><a href="http://{{$adomain->name}}" target ='_blank'>{{$adomain->name}}</a></td>
                                 <td class="text-right">
                                     
                                    
                                     <form action="{{ route('adomains.destroy', $adomain->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                         <input type="hidden" name="_method" value="DELETE">
                                         <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                         <button type="submit" class="btn btn-xs btn-danger"> Delete</button>
                                     </form>
                                 </td>
                             </tr>
                         @endforeach
                     </tbody>
                 </table>
             @else
                 <h3 class="text-center alert alert-info">Empty!</h3>
             @endif

         </div>
     </div>
	 
     <div class="row">
         <div class="col-md-12">
	 
     <form action="{{ route('adomains.store') }}" method="POST">
         <input type="hidden" name="_token" value="{{ csrf_token() }}">
		 <input type="hidden" name="site_id" id = "site_id-field" value="{{$site->id}}">
         <div class="form-group">
               <label for="user_id-field">URL</label>
             <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
             </div>
         
             <button type="submit" class="btnpete">Create alias domain</button>
        
     </form>
	 
         </div>
		 
		 <br /><br />
     </div>
	 <br /><br />
    <div class="row">
        <div class="col-md-12">
			<label for="url-field">Wordpress keys</label><i>(
these keys will be stored and encrypted)</i>
            <form action="{{ route('sites.update', $site->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    <div class="form-group">
                       <i>User</i>
                    <input type="text" id="cms_user-field" name="cms_user" class="form-control" value="{{ $user_decrypt }}"/>
                      
                    </div>
					
					
                    <div class="form-group ">
                       <i>Password</i>
                    <input type="text" id="cms_password-field" name="cms_password" class="form-control" value="{{ $password_decrypt }}"/>
                      
                    </div>
                    
                
                    <button type="submit" id ="update_button" class="btnpete">Save</button>
               
            </form>

        </div>
    </div>
	<br /><br />

	
	
@endsection

resources/views/sites/index.blade.php
@extends('layout')

@section('header')


    
        <h1>
            <img alt="w00t!" src="/toonpete.png" style="height: 204px">
			
            <a class="btnpete pull-right" href="{{ route('sites.create') }}"><i class="glyphicon glyphicon-plus"></i> Create new site</a>
        </h1>


@endsection

@section('content')
    <div class="row">
		
		
        <div class="col-md-12">
			<div class="content table-responsive table-full-width">
            @if($sites->count())
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                           <th>Name</th>
                        <th>Url</th>
                        
                        <th>Action</th>
						<th>App</th>
						<th>User</th>
						
						<th>Keys</th>
						
						
						
                         <th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($sites as $site)
                            <tr>
                                <td>{{$site->id}}</td>
                     <td>{{$site->name}}</td>           
                    <td>
					<a href="http://{{$site->url}}" target ='_blank'>{{$site->url}}</a>
					</td>
                    
                    <td>{{$site->action->name}}</td>
					<td>{{$site->app->name}}</td>
					<td>
						@if($site->user)
						{{$site->user->name}}
					    @endif
					</td>
					
					
					<td>@if(($site->cms_user) && ($site->cms_password))
						<i class="pe-7s-key"></i>
						 @endif
					</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-default" href="{{ route('sites.show', $site->id) }}"> Show</a>
                                   <a class="btn btn-xs btn-default" role="group" href="{{ route('sites.edit', $site->id) }}"> Edit</a>
								   
								    <a class="btn btn-xs btn-default" href="/sites/export?id={{$site->id}}">Export</a>
									
									@if(!$site->suspend)
									<a class="btn btn-xs btn-default" href="/sites/suspend?id={{$site->id}}">Suspend</a>
									@else
									<a class="btn btn-xs btn-default" href="/sites/site_continue?id={{$site->id}}">Continue</a>
									@endif
									
                                    <form action="{{ route('sites.destroy', $site->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $sites->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif
			</div>
        </div>
    </div>
	
	@if($exporturl != "")
		<script>
		  window.location.assign("/{{$exporturl}}");
		</script>
	@endif
	
	<script type="text/javascript">
	
	
    	$(document).ready(function(){
			
        	//demo.initChartist();
			/*
        	$.notify({
            	icon: 'pe-7s-arc',
            	message: "Welcome to the future of OZONE. Welcome to <b>Massive Server</b>"

            },{
                type: 'info',
                timer: 4000
            });
			*/

    	});
		
	</script>
	

@endsection

resources/views/sites/show.blade.php
@extends('layout')
@section('header')
    <div class="row">
        <div class="col-md-12">
       
        <form action="{{ route('sites.destroy', $site->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('sites.edit', $site->id) }}">Edit</a>
		
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
		
		<div id="loading_area">
	
		</div>
		</div>
		</div>
		

@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
			
			
            <form action="#">
                <div class="form-group">
           
					<p>Id: {{$site->id}}</p>
                </div>
				
                <div class="form-group">
                     <p>Url:
					
					 <a href="http://{{$site->url}}" target="_blank">{{$site->url}}</a></p>
                     
                </div>
				
                <div class="form-group">
                   <p> Name: {{$site->name}}</p>
                </div>
				
                <div class="form-group">
                     <p>DB Info:
                     <a class="btn btn-xs btn-primary" id ="show_db_info" href="/"> View</a></p>
					 <div id ="db_info">
					   
					</div>
                </div>
				
                <div class="form-group">
                     <p>CMS Info:
                     <a class="btn btn-xs btn-primary" id ="show_cms_info" href="/"> View</a></p>
					 <div id ="cms_info">
					   
					</div>
                </div>
				
                <div class="form-group">
                     <p>Output: </p>
                     <pre>{{$site->output}}</pre>
                </div>
				
            </form>

        </div>
    </div>
	
	<script>
	
	$(document).ready(function(){
	
	$( "#show_db_info" ).click(function() {
	  $("#loading_area").html('<div id="loading_div"></div>');
  	  $.ajax({
  	        url: "/sites/get_db_info?id={{$site->id}}",
  	        type: "get",
  	        datatype: 'json',
  	        success: function(data){
			   $("#loading_area").html('');
			   aux = "<p>";
			   aux +="<strong>DB Name: </strong>"+data['db_name']+"<br/>";
			   aux +="<strong>DB User: </strong>"+data['db_user']+"<br/>";
			   aux +="<strong>DB Password: </strong>"+data['db_password']+"<br/>";
			   aux += "</p>";
			   
			   $("#db_info").html(aux);
  	        }
				
  	  });
		
		return false;
	});
	
	
	$( "#show_cms_info" ).click(function() {
	  $("#loading_area").html('<div id="loading_div"></div>');
  	  $.ajax({
  	        url: "/sites/get_cms_info?id={{$site->id}}",
  	        type: "get",
  	        datatype: 'json',
  	        success: function(data){
			   $("#loading_area").html('');
			   aux = "<p>";
			   aux +="<strong>DB User: </strong>"+data['cms_user']+"<br/>";
			   aux +="<strong>DB Password: </strong>"+data['cms_password']+"<br/>";
			   aux += "</p>";
			   
			   $("#cms_info").html(aux);
  	        }
				
  	  });
		
		return false;
	});
	
	
	/*	
	  $.ajax({
	        url: "/sites/restart",
	        type: "get",
	        datatype: 'json',
	        success: function(data){
	          //alert("success");			
	        }
				
	  });
	
	*/
		
	});
	
	</script>

@endsection

resources/views/sites/testing.blade.php
Hola soy un testing

resources/views/sites/trash.blade.php
@extends('layout')

@section('header')
   
@endsection

@section('content')
    <div class="row">
		
		
        <div class="col-md-12">
			<div class="content table-responsive table-full-width">
				
            @if($sites->count())
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                           <th>Name</th>
                        <th>Url</th>
                        
                        <th>Action</th>
						<th>App</th>
						<th>User</th>
						
						<th>Keys</th>
						
						
						
                         <th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($sites as $site)
                            <tr>
                                <td>{{$site->id}}</td>
                     <td>{{$site->name}}</td>           
                    <td>
					<a href="http://{{$site->url}}" target ='_blank'>{{$site->url}}</a>
					</td>
                    
                    <td>{{$site->action->name}}</td>
					<td>{{$site->app->name}}</td>
					<td>
						@if($site->user)
						{{$site->user->name}}
					    @endif
					</td>
					
					
					<td>@if(($site->cms_user) && ($site->cms_password))
						<img src="check-mark-10-xxl.png" alt="Mountain View" style="width:30px;height:30px;">
						 @endif
					</td>
					

                                <td class="text-right">
                                    
								    <a class="btn btn-xs btn-primary" href="/sites/restore?id={{$site->id}}"></i>Restore</a>
									
									@if($current_user->admin)
									<a class="btn btn-xs btn-danger" href="/force_delete?id={{$site->id}}"></i>Force delete</a>
									 @endif
									
                                   
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $sites->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif
			</div>
        </div>
    </div>

@endsection